//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcaseMain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecaseEntities : DbContext
    {
        public ecaseEntities()
            : base("name=ecaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<registration> registrations { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<speciality> specialities { get; set; }
        public DbSet<@case> cases { get; set; }
        public DbSet<quote> quotes { get; set; }
    }
}
