//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcaseMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote
    {
        public int id { get; set; }
        public string description { get; set; }
        public string price { get; set; }
        public string duration { get; set; }
        public Nullable<int> lawyerid { get; set; }
        public Nullable<int> caseid { get; set; }
    }
}
